---
application:
  name: "qoverydemo"
  project: "nodejsanddb"
  organization: "QoveryCommunity"
databases:
- type: mongodb
  version: 4.2
  name: mongodbdemo
routers:
- name: "main-qoverydemo"
  routes:
  - application_name: "qoverydemo"
    paths:
    - "/*"
